name: Setup Python + pinned pip
description: Install Python and pin pip to a required version.
inputs:
  python-version:
    description: Python version to install.
    required: true
  pip-version:
    description: Exact pip version to pin after Python setup.
    required: true
runs:
  using: composite
  steps:
    - name: Setup Python
      uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d # v5.1.0
      with:
        python-version: ${{ inputs.python-version }}
    - name: Pin pip
      shell: bash
      env:
        PIP_DISABLE_PIP_VERSION_CHECK: "1"
      run: |
        set -euo pipefail
        requested='${{ inputs.pip-version }}'
        if [[ -z "${requested}" ]]; then
          echo "::error::pip-version input must not be empty"
          exit 1
        fi
        python -m pip install --upgrade "pip==${requested}"
        python -m pip --version
        actual="$(python -m pip --version | awk '{print $2}')"
        if [[ "${actual}" != "${requested}" ]]; then
          echo "::error::pip version mismatch (requested=${requested}, actual=${actual})"
          exit 1
        fi
